from django.urls import path, include
from rest_framework import routers
from api_app.views import PatientViewSet

router =routers.DefaultRouter()
router.register(r'patient', PatientViewSet)

urlpatterns = [
     path('', include(router.urls)),
     
]

# DefaultRouter: A built-in router provided by DRF that automatically generates URLs for viewsets, 
# including a default root API view.

# router.register(): Registers a viewset with the router.
# r'patient': The URL prefix for the endpoints generated by the viewset.
# PatientViewSet: The viewset that handles requests for this prefix.

# path('', include(router.urls)):
# The include(router.urls) adds all the URL patterns registered with the router to the root URL ('').
# This makes all the PatientViewSet endpoints available under the root of your API.

